server:
  port: 9011
spring:
  application:
    name: campus-ai-service-llm
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位s 默认30天
  timeout: 2592000
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  #操作日志
  is-log: true

  data-refresh-period: 600

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    path: /llm/v3/api-docs