server:
  port: 9011
spring:
  servlet:
    multipart:
      max-file-size: 50MB      # 单个文件最大大小
      max-request-size: 50MB   # 整个请求最大大小
  application:
    name: campus-ai-service-llm
  ai:
    openai:
      embedding:
        options:
          model: none
      base-url: https://api.deepseek.com
      api-key: sk-7be11144dd104c238ad3a5cae2c0f703
      chat:
        options:
          model: deepseek-chat
    vectorstore:
      milvus:
        auto-id: true
        collection-name: rag_demo_768
        client:
          host: 127.0.0.1
          port: 6783
        initialize-schema: true
        embedding-dimension: 768
    ollama:
      base-url: http://localhost:11434
      embedding:
        options:
          model: nomic-embed-text

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus_smart?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: abc123

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位s 默认30天
  timeout: 2592000
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  #操作日志
  is-log: true

  data-refresh-period: 600

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    path: /llm/v3/api-docs


mybatis-plus:
  # 1. 扫描 Mapper XML 文件 (通常放在 resources/mapper 目录下)
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  # 2. 实体类别名扫描 (XML里写 resultType 时就可以直接写类名，不用写全限定包名)
  type-aliases-package: com.nijiahao.system.domain
  configuration:
    # 3. 开发神器：开启控制台 SQL 日志打印 (上线时记得关掉或改为 File)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 4. 驼峰命名自动转换 (user_name -> userName)
    map-underscore-to-camel-case: true
  global-config:
    banner: false # 关闭启动时的 MP 字符画
    db-config:
      # 5. 全局主键策略：雪花算法 (对应你想要的 19 位 ID)
      id-type: assign_id
      # 6. 全局逻辑删除配置 (BaseEntity 里的 @TableLogic 依赖这个)
      logic-delete-field: deleted  # 数据库里的字段名
      logic-delete-value: 1        # 删除后的值
      logic-not-delete-value: 0    # 正常值
